### ISSUE TITLE
Payment Method empty must be 'NA' nor 'No identificado'.

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/cfdilib#29]
By disposition in SAT layers. When the invoice haven`t payment method, the XML must be show the label 'NA', and [here](https://github.com/Vauxoo/cfdilib/blob/master/cfdilib/templates/cfdv32.xml#L15) you return 'No identificado'. 

> Cumplimiento de requisitos en la expedición de comprobantes fiscales.
2.7.1.32. Para los efectos del artículo 29-A, fracciones I y VII, inciso c) del CFF, los contribuyentes podrán incorporar en los CFDI que expidan, la expresión NA o cualquier otra análoga, en lugar de los siguientes requisitos:
I. Régimen fiscal en que tributen conforme a la Ley del ISR.
II. Domicilio del local o establecimiento en el que se expidan los comprobantes fiscales.
### III. Forma en que se realizó el pago.

**Comment by nhomar** [comment]
@luistorresm We overwrite all False texts as No Identificado it means if the origin pass NAwhc is the legal value you will not see such element.

question: NA is valid for ALL  fields?

**Comment by luistorresm** [comment]
@nhomar 

In the last article that I send said that in this cases:

I. Régimen fiscal en que tributen conforme a la Ley del ISR.
II. Domicilio del local o establecimiento en el que se expidan los comprobantes fiscales.
III. Forma en que se realizó el pago.

Regards
