### ISSUE TITLE
Empty values as 'No suministrado'

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/cfdilib#30]
If I send a dict with empty values, the XML returned have 'No suministrado'.

But in cases as the next:

The RFC is a required value in the XSD http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd.

If I not send the RFC in dict to build the XML, I hope a message error, because I have a bad value in the XML, as in v8:

https://drive.google.com/a/vauxoo.com/file/d/0B8glieilJ0dnS2hkWF9STnhLRGs/view?usp=drivesdk

In this case the XML is generated but I can´t sign the XML.

**Comment by nhomar** [comment]
You mean an empty value should raise a traceback instead an empty ups message?

**Comment by luistorresm** [comment]
@nhomar 

In cases when the node is required in the xsd, when try confirm the XML, the lib return the error message, in a traceback, and not allow validate the invoice.

Until the values are corrected send in building the xml.

What do you think?

Regards
