### ISSUE TITLE
Error processing schema xsd using lxml>=3.6.3

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/cfdilib#43]
![inv_2016_0003_-_odoo](https://cloud.githubusercontent.com/assets/3836433/19978700/6cd27d24-a1bd-11e6-9858-066cf7ca5ec0.png)

`XMLSyntaxError: Element '{http://www.sat.gob.mx/cfd/3}Comprobante', attribute 'LugarExpedicion': [facet 'minLength'] The va
lue '' has a length of '0'; this underruns the allowed minimum length of '1'.`

Using the following script:
```bash
pip install --upgrade lxml==3.5.0  && make test  # done
pip install --upgrade lxml==3.6.0  && make test  # done
pip install --upgrade lxml==3.6.1  && make test  # done
pip install --upgrade lxml==3.6.2  && make test  # done
pip install --upgrade lxml==3.6.3  && make test  # fail
pip install --upgrade lxml==3.6.4  && make test  # fail
```

I detected that we have a fail with >=3.6.3
I will read the release notes to see if is a change of use or a new bug

Related: https://github.com/Vauxoo/mexico/issues/335

**Comment by moylop260** [comment]
I found a similar issue https://bugs.launchpad.net/lxml/+bug/1625506 with version 3.6.4 of lxml

**Comment by nhomar** [comment]
Puedes probar instalandolo de master en github?

https://github.com/lxml/lxml

**Comment by moylop260** [comment]
Using current master version from github:
`pip install --upgrade git+https://github.com/lxml/lxml.git   # Successfully installed lxml-3.7.0a0)`
The result is done!
